import './globals.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import icon from '../../public/favicon.ico'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Miswag-Challenge',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
        <link rel="icon" href={icon} />
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
